site_name: ECW Community FAQ
site_url: https://ecw-faq.readthedocs.io
nav:
  - FAQ: index.md
theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
  - kbdextension
  - attr_list
plugins:
  - mkdocs-video:
      css_style:
        aspect-ratio: "16/10"
        width: "100%"
        height: "auto"
